const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const $ = (s) => document.querySelector(s);
const ui = { menu: $('#menu'), hud: $('#hud'), countdown: $('#countdown'), count: $('#count-number'), over: $('#gameover'), score: $('#score'), coins: $('#coins'), combo: $('#combo'), speed: $('#speed'), hearts: $('#hearts'), mission: $('#mission-progress'), power: $('#powerup') };
let W, H, dpr, state = 'menu', last = 0, timer, audio;
const save = { score: +(localStorage.turboBest || 0), coins: +(localStorage.turboCoins || 0) };
const g = { lane: 1, x: 0, jump: 0, vy: 0, score: 0, coins: 0, hearts: 3, combo: 1, comboCount: 0, speed: 1, distance: 0, invincible: 0, shield: false, magnet: 0, items: [], particles: [], spawn: 0, world: 0, rush: 0, landed: 0 };
const lanes = [-.42, 0, .42];

function resize(){ dpr = Math.min(devicePixelRatio || 1, 2); W = canvas.clientWidth; H = canvas.clientHeight; canvas.width = W*dpr; canvas.height = H*dpr; ctx.setTransform(dpr,0,0,dpr,0,0); }
addEventListener('resize', resize); resize();
function sound(kind){
  try { audio ||= new AudioContext(); const o=audio.createOscillator(), gain=audio.createGain(); const f={coin:880,jump:420,hit:110,power:660,land:180}[kind]||300; o.frequency.value=f; o.type=kind==='hit'?'sawtooth':'sine'; gain.gain.setValueAtTime(.05,audio.currentTime); gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12); o.connect(gain).connect(audio.destination); o.start();o.stop(audio.currentTime+.13); } catch {}
}
function reset(){ Object.assign(g,{lane:1,x:0,jump:0,vy:0,score:0,coins:0,hearts:3,combo:1,comboCount:0,speed:1,distance:0,invincible:0,shield:false,magnet:0,items:[],particles:[],spawn:1,world:0,rush:0,landed:0}); }
function start(){ ui.menu.classList.add('hidden');ui.over.classList.add('hidden');reset(); state='count';ui.countdown.classList.remove('hidden');let n=3;ui.count.textContent=n;clearInterval(timer);timer=setInterval(()=>{n--; if(n){ui.count.textContent=n}else{ui.count.textContent='GO!';setTimeout(()=>{clearInterval(timer);ui.countdown.classList.add('hidden');ui.hud.classList.remove('hidden');state='play'},550)}},680); }
function menu(){ state='menu'; ui.hud.classList.add('hidden');ui.over.classList.add('hidden');ui.menu.classList.remove('hidden');$('#best-score').textContent=save.score.toLocaleString();$('#best-coins').textContent=save.coins; }
function end(){ state='over';ui.hud.classList.add('hidden');const newBest=g.score>save.score;if(newBest)save.score=g.score;if(g.coins>save.coins)save.coins=g.coins;localStorage.turboBest=save.score;localStorage.turboCoins=save.coins;$('#final-score').textContent=Math.floor(g.score).toLocaleString();$('#final-coins').textContent=g.coins;$('#final-best').textContent=save.score.toLocaleString();$('#new-best').classList.toggle('hidden',!newBest);ui.over.classList.remove('hidden'); }
function project(x,z){ const y=H*.21 + (1-z)*(1-z)*H*.68; const roadW=W*(.16+(1-z)*.62); return {x:W/2+x*roadW,y,scale:.3+(1-z)*1.25,roadW}; }
function add(type,lane,z,extra={}){g.items.push({type,lane,z,...extra,hit:false,phase:Math.random()*6});}
function spawn(){
  const z=1.08, d=g.distance;
  if(g.rush>0){ for(let i=0;i<3;i++)add('coin',(Math.floor(d*8+i)%3),z+i*.075,{air:i%2?0.25:0}); return; }
  const roll=Math.random();
  if(roll<.48){ const pattern=Math.floor(Math.random()*3); for(let i=0;i<4;i++)add('coin',pattern===0?Math.floor(Math.random()*3):(i+Math.floor(d))%3,z+i*.11,{air:pattern===2&&i>1?.26:0}); }
  else if(roll<.66){ const lane=Math.floor(Math.random()*3);add('obstacle',lane,z); if(g.speed>1.2&&Math.random()<.45)add('obstacle',(lane+1+Math.floor(Math.random()*2))%3,z+.04); }
  else if(roll<.84)add('enemy',Math.floor(Math.random()*3),z,{moving:Math.random()<.6});
  else if(roll<.93)add('power',Math.floor(Math.random()*3),z,{kind:Math.random()<.55?'shield':'magnet'});
  else { for(let i=0;i<5;i++)add('coin',1,z+i*.08,{air:.18}); }
}
function burst(x,y,color,count=8){for(let i=0;i<count;i++)g.particles.push({x,y,vx:(Math.random()-.5)*160,vy:(Math.random()-.6)*150,life:.5+Math.random()*.35,color});}
function collect(item,p){ if(item.hit)return;item.hit=true;const mult=g.magnet>0?2:1;g.coins+=mult;g.score+=10*mult*g.combo;g.comboCount++;g.combo=Math.min(10,1+Math.floor(g.comboCount/5));burst(p.x,p.y,'#ffe059');sound('coin'); }
function hurt(p){if(g.invincible>0)return;if(g.shield){g.shield=false;ui.power.classList.add('hidden');g.invincible=1;burst(p.x,p.y,'#9bf5e0',18);sound('power');return}g.hearts--;g.combo=1;g.comboCount=0;g.invincible=1.5;burst(p.x,p.y,'#ff6e75',22);sound('hit');if(g.hearts<=0)setTimeout(end,350);}
function update(dt){
  if(state!=='play') return; g.distance+=dt*g.speed;g.speed=1+Math.min(1.25,g.distance/36);g.score+=dt*10*g.speed*g.combo;g.x+=(lanes[g.lane]-g.x)*Math.min(1,dt*11);if(g.jump>0||g.vy){g.vy-=dt*2.75;g.jump+=g.vy*dt;if(g.jump<=0){g.jump=0;g.vy=0;g.landed=.16;sound('land');}}g.invincible-=dt;g.magnet-=dt;g.landed-=dt;g.rush-=dt;
  g.spawn-=dt*g.speed;if(g.spawn<=0){spawn();g.spawn=.52+Math.random()*.34-Math.min(.19,g.distance*.003)}
  for(const it of g.items){it.z-=dt*(.25+.3*g.speed)*(g.rush>0?.75:1); if(it.moving)it.lane=1+Math.sin(g.distance*2.2+it.phase)*.75;const p=project(lanes[Math.round(it.lane)]??0,it.z);if(!it.hit&&it.z<.19&&it.z>-.06&&Math.abs(g.x-(lanes[Math.round(it.lane)]??0))<.16){if(it.type==='coin'){if(g.jump>it.air-.07||!it.air)collect(it,p); }else if(it.type==='power'){it.hit=true;if(it.kind==='shield'){g.shield=true;ui.power.textContent='🛡 SHIELD READY'}else{g.magnet=8;ui.power.textContent='🧲 SPARK MAGNET · 8s'}ui.power.classList.remove('hidden');burst(p.x,p.y,'#8ff2e1',16);sound('power')}else if(g.jump<.26)hurt(p);else {it.hit=true;g.score+=25*g.combo;g.comboCount++;burst(p.x,p.y,'#fff0a3',6)}}}
  g.items=g.items.filter(i=>i.z>-.16&&!i.hit);for(const p of g.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=280*dt;p.life-=dt}g.particles=g.particles.filter(p=>p.life>0);
  if(g.distance>0&&Math.floor(g.distance)%42===0&&g.world!==Math.floor(g.distance/42)){g.world=Math.floor(g.distance/42);g.rush=10;}
  ui.score.textContent=Math.floor(g.score).toString().padStart(6,'0');ui.coins.textContent=String(g.coins).padStart(2,'0');ui.combo.textContent=`x${g.combo}`;ui.speed.textContent=`⚡ ${g.speed.toFixed(1)}x`;ui.hearts.textContent='♥ '.repeat(g.hearts)+'♡ '.repeat(3-g.hearts);ui.mission.textContent=`${Math.min(g.coins,30)} / 30`;if(g.magnet<=0&&!g.shield)ui.power.classList.add('hidden');if(g.rush>0){ui.power.textContent=`✦ SPARK RUSH · ${Math.ceil(g.rush)}s`;ui.power.classList.remove('hidden')}
}
function hill(x,y,w,h,color){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x-w,y);ctx.quadraticCurveTo(x,y-h,x+w,y);ctx.lineTo(x+w,H*.52);ctx.lineTo(x-w,H*.52);ctx.fill();}
function draw(){
  const t=performance.now()/1000;ctx.clearRect(0,0,W,H);const palettes=[['#75d7e8','#d6f6d2','#42bc87','#3b8b65'],['#f7bd63','#ffe0a1','#e98442','#b95c43'],['#8fd6c3','#c3efd1','#287b6f','#19564f'],['#a6d7f5','#e6f9ff','#77acd3','#5b76a6']];const pal=palettes[Math.floor(g.distance/42)%palettes.length];
  const sky=ctx.createLinearGradient(0,0,0,H*.6);sky.addColorStop(0,pal[0]);sky.addColorStop(1,pal[1]);ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.65;for(let i=0;i<5;i++)hill((i-.4)*W/4,H*.46,W*.25,H*(.06+(i%2)*.04),pal[2]);ctx.globalAlpha=1;
  // road perspective
  ctx.fillStyle='#1d3655';ctx.beginPath();ctx.moveTo(W*.41,H*.2);ctx.lineTo(W*.59,H*.2);ctx.lineTo(W*1.08,H);ctx.lineTo(W*-.08,H);ctx.fill();ctx.fillStyle='#52667c';ctx.beginPath();ctx.moveTo(W*.425,H*.2);ctx.lineTo(W*.575,H*.2);ctx.lineTo(W*.98,H);ctx.lineTo(W*.02,H);ctx.fill();
  for(let z=0;z<1;z+=.055){let q=(z+(g.distance*.18)% .055)%1,p=project(0,q);ctx.strokeStyle=q%0.11<.055?'#f7f0d6':'#e3d6b9';ctx.lineWidth=Math.max(1,p.scale*2);ctx.beginPath();ctx.moveTo(W/2-p.roadW*.34,p.y);ctx.lineTo(W/2+p.roadW*.34,p.y);ctx.stroke();}
  for(const x of [-1/3,1/3]){ctx.strokeStyle='#dce7e7aa';ctx.lineWidth=4;ctx.setLineDash([12,12]);ctx.beginPath();ctx.moveTo(W/2+x*W*.16,H*.2);ctx.lineTo(W/2+x*W*.63,H);ctx.stroke();ctx.setLineDash([]);}
  // roadside decor
  for(let z=.15;z<1;z+=.13){let q=(z+(g.distance*.11)% .13)%1,p=project(0,q);for(const side of [-1,1]){ctx.fillStyle=pal[3];ctx.beginPath();ctx.arc(W/2+side*(p.roadW+20),p.y-17*p.scale,12*p.scale,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6a452e';ctx.fillRect(W/2+side*(p.roadW+20)-2*p.scale,p.y-2*p.scale,4*p.scale,16*p.scale)}}
  const sorted=[...g.items].sort((a,b)=>b.z-a.z);for(const it of sorted){const p=project(lanes[Math.round(it.lane)]??0,it.z);drawItem(it,p,t)}drawKart(t);for(const p of g.particles){ctx.globalAlpha=Math.max(0,p.life*1.3);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,4,0,7);ctx.fill()}ctx.globalAlpha=1;
}
function drawItem(it,p,t){if(it.hit)return;const s=p.scale;if(it.type==='coin'){ctx.save();ctx.translate(p.x,p.y-it.air*H*s*.38);ctx.rotate(t*5);ctx.fillStyle='#ffe052';ctx.beginPath();ctx.ellipse(0,0,10*s,14*s,0,0,7);ctx.fill();ctx.strokeStyle='#e89528';ctx.lineWidth=3*s;ctx.stroke();ctx.fillStyle='#fff5a5';ctx.fillRect(-2*s,-7*s,4*s,14*s);ctx.restore();return}if(it.type==='power'){ctx.fillStyle=it.kind==='shield'?'#75ead1':'#b28cf5';ctx.beginPath();ctx.arc(p.x,p.y-16*s,17*s,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.font=`${18*s}px sans-serif`;ctx.textAlign='center';ctx.fillText(it.kind==='shield'?'🛡':'🧲',p.x,p.y-10*s);return}ctx.save();ctx.translate(p.x,p.y);if(it.type==='obstacle'){ctx.fillStyle='#fa8b4f';ctx.fillRect(-17*s,-24*s,34*s,25*s);ctx.strokeStyle='#823e35';ctx.lineWidth=3*s;ctx.strokeRect(-17*s,-24*s,34*s,25*s);ctx.strokeStyle='#ffd970';ctx.beginPath();ctx.moveTo(-15*s,-22*s);ctx.lineTo(14*s,-2*s);ctx.moveTo(14*s,-22*s);ctx.lineTo(-14*s,-2*s);ctx.stroke()}else{ctx.fillStyle='#a65a8b';ctx.beginPath();ctx.ellipse(0,-17*s,18*s,15*s,0,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-6*s,-19*s,4*s,0,7);ctx.arc(6*s,-19*s,4*s,0,7);ctx.fill();ctx.fillStyle='#283655';ctx.beginPath();ctx.arc(-6*s,-19*s,2*s,0,7);ctx.arc(6*s,-19*s,2*s,0,7);ctx.fill();ctx.strokeStyle='#5b3568';ctx.lineWidth=5*s;ctx.beginPath();ctx.moveTo(-13*s,-4*s);ctx.lineTo(-20*s,2*s);ctx.moveTo(13*s,-4*s);ctx.lineTo(20*s,2*s);ctx.stroke()}ctx.restore();}
function drawKart(t){const p=project(g.x,.07),x=p.x,y=H*.79-g.jump*H*.34;ctx.save();ctx.translate(x,y);if(g.invincible>0&&Math.floor(t*14)%2===0)ctx.globalAlpha=.35;ctx.rotate(g.landed>0?-.07:0);ctx.fillStyle='#202d4a';ctx.beginPath();ctx.ellipse(-28,14,20,18,0,0,7);ctx.ellipse(30,14,20,18,0,0,7);ctx.fill();ctx.fillStyle='#68dfbb';ctx.beginPath();ctx.roundRect(-48,-5,99,31,17);ctx.fill();ctx.fillStyle='#25547b';ctx.fillRect(-33,11,68,14);ctx.fillStyle='#c8fffa';ctx.beginPath();ctx.moveTo(-16,-5);ctx.lineTo(20,-5);ctx.lineTo(13,-23);ctx.lineTo(-5,-23);ctx.fill();ctx.fillStyle='#f8b783';ctx.beginPath();ctx.arc(0,-37,15,0,7);ctx.fill();ctx.fillStyle='#f27065';ctx.beginPath();ctx.roundRect(-18,-54,35,12,7);ctx.fill();ctx.fillStyle='#263452';ctx.fillRect(-13,-31,26,5);ctx.fillStyle='#ffe056';ctx.beginPath();ctx.arc(-23,11,7,0,7);ctx.arc(26,11,7,0,7);ctx.fill();if(g.shield){ctx.strokeStyle='#9cf7e3aa';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,-10,65,0,7);ctx.stroke()}ctx.restore();}
function loop(now){const dt=Math.min(.04,(now-last)/1000||0);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function key(e){if(['ArrowLeft','ArrowRight','a','d','A','D',' '].includes(e.key))e.preventDefault();if(state==='menu'&&e.code==='Space')start();if(state==='play'){if(e.key==='ArrowLeft'||e.key==='a'||e.key==='A')g.lane=Math.max(0,g.lane-1);if(e.key==='ArrowRight'||e.key==='d'||e.key==='D')g.lane=Math.min(2,g.lane+1);if(e.code==='Space'&&g.jump===0){g.vy=.96;g.jump=.01;sound('jump')}}}addEventListener('keydown',key);
$('#play').onclick=start;$('#again').onclick=start;$('#main-menu').onclick=menu;$('#howto').onclick=()=>$('#instructions').classList.remove('hidden');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#instructions').classList.add('hidden'));menu();
